# Test

### Error Test

```TSX
  import { getCountValue } from 'utils/DateUtils';

describe('getCountValue', () => {
  it('falsy한 값이 들어오면 Error문구를 띄워준다', () => {
    expect(() => getCountValue(null)).toThrowError('scope 값이 없습니다.');
  });

  it('falsy한 값이 들어오면 Error문구를 띄워준다', () => {
    expect(getCountValue(null)).toThrowError('scope 값이 없습니다.');
  });
});
```

- 위와 같이 작성하면 첫 번째는 통과하는 반면, 두 번째는 Error가 발생한다.
- 두 번째는 expect 함수의 인자로 함수를 넣어주었기 때문에, 함수가 실행되는 것이 아니라 함수 자체를 넘겨주는 것이다.
- 함수가 실행 될 때 에러가 발생해야 하기 때문에 첫 번째와 같이 작성해주어야한다.
